# ["1"]["inputs"]["unet_name"] = 
# ["1"]["inputs"]["weight_dtype"] = 
# ["2"]["inputs"]["clip_name1"] = 
# ["2"]["inputs"]["clip_name2"] = 
# ["3"]["inputs"]["vae_name"] = 
# clip vision
# ["4"]["inputs"]["clip_name"] = 
# style model
# ["5"]["inputs"]["style_model_name"] = 
# ["6:51"]["inputs"]["custom_width"] = 
# ["6:51"]["inputs"]["custom_height"] = 
# # positive
# ["6:6"]["inputs"]["text"] = 
# ["6:26"]["inputs"]["guidance"] = 
# ["6:30"]["inputs"]["max_shift"] = 
# ["6:30"]["inputs"]["base_shift"] = 
# ["6:25"]["inputs"]["noise_seed"] = 
# ["6:16"]["inputs"]["sampler_name"] = 
# ["6:17"]["inputs"]["scheduler"] = 
# ["6:17"]["inputs"]["steps"] = 
# ["6:17"]["inputs"]["denoise"] = 
# ["6:27"]["inputs"]["batch_size"] = 
# ["9"]["inputs"]["image"] = 
# ["7:52"]["inputs"]["crop"] = 
# ["7:53"]["inputs"]["strength"] = 
# ["7:53"]["inputs"]["strength_type"] = 
# ["10"]["inputs"]["image"] = 
# ["8:52"]["inputs"]["crop"] = 
# ["8:53"]["inputs"]["strength"] = 
# ["8:53"]["inputs"]["strength_type"] = 
# ["12"]["inputs"]["lora_name_1"] = 
# ["12"]["inputs"]["model_weight_1"] = 
# ["12"]["inputs"]["lora_name_2"] = 
# ["12"]["inputs"]["model_weight_2"] = 
# ["12"]["inputs"]["lora_name_3"] = 
# ["12"]["inputs"]["model_weight_3"] = 
# ["12"]["inputs"]["lora_name_4"] = 
# ["12"]["inputs"]["model_weight_4"] = 