# ["1"]["inputs"]["unet_name"] = 
# ["1"]["inputs"]["weight_dtype"] = 
# ["2"]["inputs"]["clip_name1"] = 
# ["2"]["inputs"]["clip_name2"] = 
# ["3"]["inputs"]["vae_name"] = 
# clip vision
# ["4"]["inputs"]["clip_name"] = 
# model patch
# ["5"]["inputs"]["name"] = 
# ["6"]["inputs"]["lora_name"] = 
# ["6"]["inputs"]["strength_model"] = 
# ["7:125"]["inputs"]["custom_width"] = 
# ["7:125"]["inputs"]["custom_height"] = 
# # positive
# ["7:6"]["inputs"]["text"] = 
# ["7:137"]["inputs"]["boolean_value"] = 
# ["7:109"]["inputs"]["upscale_method"] = 
# ["7:109"]["inputs"]["largest_size"] = 
# ["7:130"]["inputs"]["guidance"] = 
# ["7:124"]["inputs"]["max_shift"] = 
# ["7:124"]["inputs"]["base_shift"] = 
# ["7:121"]["inputs"]["noise_seed"] = 
# ["7:117"]["inputs"]["sampler_name"] = 
# ["7:118"]["inputs"]["scheduler"] = 
# ["7:118"]["inputs"]["steps"] = 
# ["7:118"]["inputs"]["denoise"] = 
# ["7:119"]["inputs"]["batch_size"] = 
# subject image
# ["10"]["inputs"]["image"] = 
# ["11"]["inputs"]["image"] = 
# ["8:111"]["inputs"]["crop"] = 
# ["12"]["inputs"]["image"] = 
# ["9:111"]["inputs"]["crop"] = 
# ["15"]["inputs"]["lora_name_1"] = 
# ["15"]["inputs"]["model_weight_1"] = 
# ["15"]["inputs"]["lora_name_2"] = 
# ["15"]["inputs"]["model_weight_2"] = 
# ["15"]["inputs"]["lora_name_3"] = 
# ["15"]["inputs"]["model_weight_3"] = 
# ["15"]["inputs"]["lora_name_4"] = 
# ["15"]["inputs"]["model_weight_4"] = 