# ["1"]["inputs"]["unet_name"] = 
# ["1"]["inputs"]["weight_dtype"] = 
# ["2"]["inputs"]["clip_name"] = 
# ["3"]["inputs"]["vae_name"] = 
# # positive
# ["4:403"]["inputs"]["prompt"] = 
# # negative
# ["4:404"]["inputs"]["prompt"] = 
# ["4:407"]["inputs"]["shift"] = 
# ["4:411"]["inputs"]["strength"] = 
# ["4:406"]["inputs"]["cfg"] = 
# ["4:406"]["inputs"]["sampler_name"] = 
# ["4:406"]["inputs"]["scheduler"] = 
# ["4:406"]["inputs"]["steps"] = 
# ["4:406"]["inputs"]["denoise"] = 
# ["4:406"]["inputs"]["seed"] = 
# ["5"]["inputs"]["image"] = 
# ["7"]["inputs"]["lora_name_1"] = 
# ["7"]["inputs"]["model_weight_1"] = 
# ["7"]["inputs"]["lora_name_2"] = 
# ["7"]["inputs"]["model_weight_2"] = 
# ["7"]["inputs"]["lora_name_3"] = 
# ["7"]["inputs"]["model_weight_3"] = 
# ["7"]["inputs"]["lora_name_4"] = 
# ["7"]["inputs"]["model_weight_4"] = 