options = [
  "surprised expression",
  "taken aback expression",
  "astonished expression",
  "amazed expression",
  "shocked expression",
  "stunned expression",
  "astonuded expression",
  "flabbergasted expression"
]