options = [
  "surprised expression",
  "taken aback expression",
  "startled expression",
  "awe expression",
  "awestruck expression",
  "astonished expression",
  "amazed expression",
  "incredulous expression",
  "disbelief expression",
  "shocked expression",
  "stunned expression",
  "astounded expression",
  "stupefied expression",
  "flabbergasted expression",
  "dismayed expression",
  "appalled expression"
]